### ISSUE TITLE
ListTransform not working with subclassed types

### ISSUE THREAD

**Issue by seeppp** [Jakenberg/ObjectMapper-Realm#11]
I have an object with a list as a variable. the type of the list is, say: ```Child```. The child class does inherit from ```Parent```. To get it work with Realm, the Type of the Parent class should be ```StaticMappable```, rather then ```Mappable```.

> Subclassing and Realm: https://github.com/Hearst-DD/ObjectMapper/issues/462

Now I stuck on this:
![bildschirmfoto 2017-02-13 um 18 16 27](https://cloud.githubusercontent.com/assets/3663377/22894243/9674bfba-f218-11e6-8a76-bfa2a0323459.png)

I found in your struct ListTransform, that the generic Type T has to be ```Mappable```. Why not ```BaseMappable```? This will solve the compile-error.

To reproduce:
```
import ObjectMapper
import RealmSwift
import ObjectMapper_Realm

class Parent: Object, StaticMappable {
    dynamic var name = ""
    
    class func objectForMapping(map: Map) -> BaseMappable? {
        return Parent()
    }
    
    func mapping(map: Map) {
        name <- map["name"]
    }
}

class Child: Parent {
    dynamic var onlyMyType = 0
    
    override class func objectForMapping(map: Map) -> BaseMappable? {
        return Child()
    }
    
    override func mapping(map: Map) {
        super.mapping(map: map)
        onlyMyType <- map["only_my_type"]
    }
}

class ManyChilds: Object, Mappable {
    var childs = List<Child>()
    
    required convenience init?(map: Map) {
        self.init()
    }
    
    func mapping(map: Map) {
        childs <- (map["childs"], ListTransform<Child>()) // here we have the error, because Child is not of type `Mappable`
    }
}
```

ObjectMapper (2.2.2)
RealmSwift (2.4.2)
ObjectMapper+Realm (0.2)

Swift 3.0.2
Xcode: 8.2.1

**Comment by 0xjmp** [comment]
https://github.com/Jakenberg/ObjectMapper-Realm/commit/3a1d2a019fbf9f903b3c014a754ea431c49ef6ae should fix this issue. Please re-open if it persists 👍
