### ISSUE TITLE
Update a readme.

### ISSUE THREAD

**Issue by NikKovIos** [Jakenberg/ObjectMapper-Realm#12]
Doesn't it should be dynamic var's in readme?

Could you please write more examples like here https://github.com/zendobk/RealmMapper

**Comment by develth** [comment]
+1  i just struggled about it and wondered why i cannot access my retrieved data.

**Comment by NikKovIos** [comment]
You can look here https://github.com/NikKovIos/ObjectMapper_RealmSwift

**Comment by 0xjmp** [comment]
README updated
