### ISSUE TITLE
Can't use ListTransform with lists defined with let

### ISSUE THREAD

**Issue by kashifshaikh** [Jakenberg/ObjectMapper-Realm#13]
Realm docs say to define list properties with let:

Please see: https://realm.io/docs/swift/latest/#property-attributes

So the ListTransform does not work as it returns a new list and you can't overwrite the list.

**Comment by 0xjmp** [comment]
Using a property defined as `let` is not the intended use of `ListTransform`. ObjectMapper fundamentally requires the ability to mutate a property (`var`).
