### ISSUE TITLE
Can't use dynamic var with List<Object>

### ISSUE THREAD

**Issue by ghost** [Jakenberg/ObjectMapper-Realm#15]
This feature doesn't work, so the readme should reflect it. The effect of this is you can't use ListTransform and still access properties via dot syntax.

Unless I'm missing something.

**Comment by ghost** [comment]
I'll provide a code example when I'm back at my desk.

**Comment by 0xjmp** [comment]
A code example would be great. Also, please specify which version you're using.

Closing for now... feel free to re-open with the above.
