### ISSUE TITLE
Carthage import failed

### ISSUE THREAD

**Issue by retX0** [Jakenberg/ObjectMapper-Realm#16]
I edit the Cartfile, put `github "jakenberg/ObjectMapper-Realm"` in to Cartfile, but when carthage update, there no framework on iOS folder.

**Comment by 0xjmp** [comment]
@xnxin you need to manually drag and drop the framework from the `Carthage/Build` folder to [Project Target] -> General -> Linked Frameworks and Libraries. 

Carthage outlines this step and those that encapsulate it [here](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos)
