### ISSUE TITLE
Facing difficulty in creating Model for following JSON Structure.

### ISSUE THREAD

**Issue by imobdev-nucitrus** [Jakenberg/ObjectMapper-Realm#17]
`
{
  "title": "Recent Uploads tagged dogs",
  "link": "https://www.flickr.com/photos/tags/dogs/",
  "description": "",
  "modified": "2017-05-24T04:51:14Z",
  "generator": "https://www.flickr.com",
  "items": [
    {
      "title": "20170520-NSW3-3549",
      "link": "https://www.flickr.com/photos/k9mom2008/34857898535/",
      "media": {
        "m": "https://farm5.staticflickr.com/4250/34857898535_aebc9c9570_m.jpg"
      },
      "date_taken": "2017-05-20T13:33:33-08:00",
      "description": " <p><a href=\"https://www.flickr.com/people/k9mom2008/\">K9Mom2008</a> posted a photo:</p> <p><a href=\"https://www.flickr.com/photos/k9mom2008/34857898535/\" title=\"20170520-NSW3-3549\"><img src=\"https://farm5.staticflickr.com/4250/34857898535_aebc9c9570_m.jpg\" width=\"240\" height=\"160\" alt=\"20170520-NSW3-3549\" /></a></p> ",
      "published": "2017-05-24T04:51:14Z",
      "author": "nobody@flickr.com (\"K9Mom2008\")",
      "author_id": "21376052@N06",
      "tags": "dogs nsw3"
    }
  ]
}`

I am able to create whole structure, except `media` which contains sub `Dictionary` 
How do I handle for that?

**Comment by 0xjmp** [comment]
This question is better suited for [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper/issues). Although, I would suggest looking at:
1. What generic constraints are defined for `Dictionary`'s key and value? Do they match your data set? (e.g. `Dictionary<String, String>`).
2. `media` is part of it's own dictionary: are `items` being serialized. If so, Are they serialized into objects, or a dictionary? If the former, are other fields properly set? If the latter, I suspect ObjectMapper won't automatically map multiple levels of _arbitrary_ dictionaries (try defining them as their own classes).
3. Try setting a breakpoint in `map` at the line where serialization of `items` and/or `media` occur. You can either print the value to rule out OM issues, or you can step into the library to see where the data is being dropped.

That's all that comes to mind. I think one of those options should send you in a fruitful path. If not, I would suggest contacting the maintainers of OM.
