### ISSUE TITLE
Swift 3 

### ISSUE THREAD

**Issue by kimdv** [Jakenberg/ObjectMapper-Realm#2]
Is there any plans to update to Swift 3 ? 

And the latest version of ObjectMapper and Realm ? 

//Kim

**Comment by akovalov** [comment]
I've submitted a PR #3  for this.

**Comment by codytwinton** [comment]
@Jakenberg - Any update on releasing this update to Cocoapods?

**Comment by codytwinton** [comment]
@Jakenberg - Thanks for releasing, but can you push the release to Cocoapods? Currently using this:

`pod 'ObjectMapper+Realm', :git => 'https://github.com/Jakenberg/ObjectMapper-Realm.git', :branch => 'master'`

Would love to move to just using:

`pod 'ObjectMapper+Realm'`

**Comment by 0xjmp** [comment]
Hi folks, sorry for the delays; rough month! I just released `0.2` to cocoapods. Enjoy! 🤖
