### ISSUE TITLE
Feature request: mapping realm object -> object

### ISSUE THREAD

**Issue by Gargo** [Jakenberg/ObjectMapper-Realm#21]
Realm objects are linked with managed context and so they can be used only in the same thread (maybe in the same run loop). Could you add a mapping to something which is not linked managed context

**Comment by bibekdari** [comment]
Looking for that.

**Comment by 0xjmp** [comment]
@Gargo Realm doesn't use "managed contexts" like Core Data does so I'm a little unclear on what you're asking. Could you provide an example?

Just so you know, ObjectMapper already maps `Array` properties of a model:
```swift
class User {
    dynamic var username: NSString?
    var friends: Array<User>?

    required convenience init(map: Map) throws {
        self.init()
    }

    func mapping(map: Map) {
        username              <- map["username"]
        friends               <- map["friends"]
    }
}
```

**Comment by 0xjmp** [comment]
As of `v0.9`, you are welcome to try out the new `onSerialize` method. Hopefully that helps provide what you need!
```
class User: Object, Mappable {
    
    func mapping(map: Map) {
        username              <- map["username"]
        friends               <- (map["friends"], ListTransform<User>(onSerialize: onSerialize))
    }
    
    private func onSerialize(users: List<User>) {
        let realm = Storage.shared.realm
        try! realm.write {
            realm.add(users, update: .modified)
        }
    }
}
```
