### ISSUE TITLE
Carthage build failed

### ISSUE THREAD

**Issue by polgass** [Jakenberg/ObjectMapper-Realm#22]
Hi,

I'm getting this error when installing the library using Carthage:

*** Building scheme "ObjectMapper+Realm" in ObjectMapper+Realm.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/ml/Developer/Carthage_DuckDuckDefine/Carthage/Checkouts/ObjectMapper-Realm/ObjectMapper+Realm.xcworkspace -scheme ObjectMapper+Realm -configuration Release -derivedDataPath /Users/ml/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/ObjectMapper-Realm/0.5 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/g2/x_y6vlnx547cwbz_mkgnc7v00000gn/T/ObjectMapper-Realm SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO 

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/g2/x_y6vlnx547cwbz_mkgnc7v00000gn/T/carthage-xcodebuild.siJOyX.log

This is what's in the Cartfile:

github "Jakenberg/ObjectMapper-Realm"

When I ran **carthage update --platform iOS**, the installation stops, producing the error above. 

Any help would be very much appreciated.

**Comment by fernandomatal** [comment]
Any updates on this?

**Comment by 0xjmp** [comment]
I just tried installing with Carthage and things went okay. Please try again with v0.8 or above, and re-open the issue if problem persists.
