### ISSUE TITLE
support watchos

### ISSUE THREAD

**Issue by dNadiia** [Jakenberg/ObjectMapper-Realm#23]
Do you have any plans to support watchos?
`(watchOS 4.0) is not compatible with ObjectMapper+Realm (0.5), which does not support watchos`

**Comment by 0xjmp** [comment]
Hi @dNadiia,

Apologies that I couldn't get around to doing this sooner, but I'm pleased to let you know that `ObjectMapper+Realm` now supports watchOS in [0.6](https://github.com/Jakenberg/ObjectMapper-Realm/releases/tag/0.6) :)

**Comment by dNadiia** [comment]
Thanks!
