### ISSUE TITLE
Help with JSON:API + Realm + ObjectMapper

### ISSUE THREAD

**Issue by rromanchuk** [Jakenberg/ObjectMapper-Realm#25]
I have been struggling to find any implementation that supports a  robust API with http://jsonapi.org/format/   I'm especially stuck when it comes to translating partial updates that support the json api spec. 

```swift
class Challenge: Object, Mappable {
    
    @objc dynamic var id = ""
    @objc dynamic var action = ""

     var players = List<Player>()
     
      override static func primaryKey() -> String? {
        return "id"
    }

    func mapping(map: Map) {
        
        id <- map["id"]
        action <- map["attributes.action"]
        players <- (map["relationships.players.data"], ListTransform<Player>())
    }
}
```

Now the problem i'm having is these relationships are stubs, they are partial updates. My problem is if realm already has these items they are are completely nilled out. It causes complete chaos because as these relationships are added, existing properties get wiped, and then come back once a again once the full compound document gets processed from the `include`

```swift
let json = JSON(data as Any)
guard let payloadDict = json.dictionary, let dataDict = payloadDict["data"], let includedArray = payloadDict["included"]?.arrayObject else { abort() }
guard let challenge = Mapper<Challenge>().map(JSONObject: dataDict) else {
    abort()
}
let realm = try! Realm()
// OK this is going to create a bunch of stubbed players nilling out the entire model if it already exists
try! localRealm.write {
    localRealm.create(type(of: object), value: challenge, update: true)
}

guard let players = Mapper<Player>().mapArray(JSONObject: includedArray) else {
    abort()
}
// .... truncated, save players in realm write block
```
The other problem is that compounds/includes are put into a `included` array of any type that was asked to be included, so even `Mapper<Player>().mapArray(JSONObject: includedArray)` isn't very correct, it is only accidentally correct.  This is now becoming extremely unwieldy to manage

Example response, this is for a collection
```json
{
  "data": [
    {
      "id": "82172c36-ff02-44c5-9532-5cfb017a35b1",
      "type": "challenge",
      "attributes": {
        "action": "Dr. Greger’s Daily Dozen",
        "created_at": "2018-04-30T20:51:26.869Z",
      },
      "relationships": {
        "players": {
          "data": [
            {
              "id": "d38fc35f-618a-437a-9aed-8f9abe9f8ef0",
              "type": "player"
            },
            {
              "id": "2032d502-e571-4264-8842-899b29d8f5af",
              "type": "player"
            },
            {
              "id": "8e274631-8086-4e25-9098-6edd0b9ef50b",
              "type": "player"
            },
            {
              "id": "d511f92b-ad76-48df-8260-189ddb4bbb42",
              "type": "player"
            },
          ]
        },
        "owner": {
          "data": {
            "id": "98f8191b-6baf-485f-b3e3-e13775268b21",
            "type": "user"
          }
        }
      }
    }],
"included": [
    {
      "id": "d38fc35f-618a-437a-9aed-8f9abe9f8ef0",
      "type": "player",
      "attributes": {
        .... truncated
      }
    },]
```

This is what i *actually* need the mapper to do 
```swift

    id <- map["id"]
    action <- map["attributes.action"]
try! realm.write {
    players <- realm.create(Player.self, value: [{"id": "1"}, {"id": "2"}], update: true) // PARTIAL UPDATE FOR JSON API SPEC
}

```

I'm at the point where I have stopped trying to model relationships with Realm anymore. I simply store foreign keys and use predicates. I haven't seen a single example on the internet of someone using json api and realm. I can only find lots of bikeshedding, or json api with nothing more complicated than reading attritubes, no relationships, no compound documents. If anyone can point me in the write direction, would be greatly appreciated!

**Comment by beamercola** [comment]
@rromanchuk i feel you. this is really painful.  nobody wants to talk about it.

**Comment by 0xjmp** [comment]
You've been heard. I was finally able to sit down and write something up that I hope meets your needs. In `v0.9` you will have access to an `onSerialize` method. It allows you to control what happens to your newly serialized objects:
```
class User: Object, Mappable {
    
    func mapping(map: Map) {
        username              <- map["username"]
        friends               <- (map["friends"], ListTransform<User>(onSerialize: onSerialize))
    }
    
    private func onSerialize(users: List<User>) {
        let realm = Storage.shared.realm
        try! realm.write {
            realm.add(users, update: .modified)
        }
    }
}
```
