### ISSUE TITLE
Data not getting persisted in Realm

### ISSUE THREAD

**Issue by kalrashubham49** [Jakenberg/ObjectMapper-Realm#27]
Even after using ListTransform , data is not getting persisted

**Comment by 0xjmp** [comment]
@kalrashubham49 thank you for using this library 🙌 

Please refer to [this](https://github.com/Jakenberg/ObjectMapper-Realm/issues/26#issuecomment-390688473) & [this](https://github.com/Jakenberg/ObjectMapper-Realm/issues/7) for comprehensive answers to your issue.

In short, data persistence is a task of _Realm_. Associated `Object` instances will not be automatically persisted. You need to save _each_ set of instances that you intend to store on disk. I recommend doing this within a single `write` closure for optimal performance.
