### ISSUE TITLE
Swift 4?

### ISSUE THREAD

**Issue by chatarveer** [Jakenberg/ObjectMapper-Realm#28]
I have been used it, in my project, but now I am unable to move to new beta xcode, which doesn't support version of Swift used in ObjectMapper-Realm.

**Comment by aadilHaffez** [comment]
@veer-suthar any update on that?

**Comment by chatarveer** [comment]
I removed this pod completely, & wrote my own extension to parse Array, rest all work done by   pod 'ObjectMapper'.

**Comment by osrl** [comment]
Can you share your extension? @veer-suthar

**Comment by seankcw** [comment]
@veer-suthar I have the same question

**Comment by radekwilczak** [comment]
edit:
I've found that new version (6.0.1) of ObjectMapperAdditions have exacly what are we looking for:
https://github.com/APUtils/ObjectMapperAdditions/blob/master/ObjectMapperAdditions/Classes/Realm/RealmListTransform.swift

**Comment by 0xjmp** [comment]
New release [`0.7`](https://github.com/Jakenberg/ObjectMapper-Realm/releases/tag/0.7) should give you what you're looking for.
