### ISSUE TITLE
Mapping an array of Int - List<Int>()

### ISSUE THREAD

**Issue by christoff-1992** [Jakenberg/ObjectMapper-Realm#30]
Whats everyone doing regarding to mapping an array of Int to a list of integers now that this is supported in Realm?

**e.g** "ids": [123, 456, 789]

Would this be acceptable?

```Swift
import Foundation
import ObjectMapper
import RealmSwift

public struct IntListTransform: TransformType {

    public typealias Object = List<Int>
    public typealias JSON = [Any]

    public func transformFromJSON(_ value: Any?) -> List<Int>? {
        guard let intValues = value as? [Int] else {
            return nil
        }
        let objects = intValues.compactMap {
            Int($0)
        }
        let list = List<Int>()
        list.append(objectsIn: objects)
        return list
    }

    public func transformToJSON(_ value: List<Int>?) -> [Any]? {
        Fatal.notImplemented("Implementation not required")
    }
}
```

**Comment by Busta117** [comment]
this solution is not generic, so, you need to create a new transform for int, float, boo, string and so... the best solution is making a transform with generics like currently is implemented but adding something that accept native types

**Comment by Busta117** [comment]
check this:  https://gist.github.com/Busta117/78a1aded0a73cf1c4f61bfda113a86c8
no need to add a `ListTransform()`
just left the `listVariable <- map["key"]` and it will map it

**Comment by christoff-1992** [comment]
@Busta117 - Thanks for the comment, I will take a look at this :)
