### ISSUE TITLE
Lots of warnings regarding public modifier which is redundant.

### ISSUE THREAD

**Issue by Skudoku** [Jakenberg/ObjectMapper-Realm#31]
Can you please get all these public modifiers out so that I don't have to keep updating the pod after a pod update, not sure since when this is not needed anymore, but it's throwing warnings now.

**Comment by 0xjmp** [comment]
Fixed in [`0.7`](https://github.com/Jakenberg/ObjectMapper-Realm/releases/tag/0.7).
