### ISSUE TITLE
SWIFT_VERSION '3.0' is unsupported

### ISSUE THREAD

**Issue by maasim94** [Jakenberg/ObjectMapper-Realm#34]
Pod install is giving me this error

SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'ObjectMapper+Realm')

**Comment by uwemeier-sclable** [comment]
should be fixed by https://github.com/Jakenberg/ObjectMapper-Realm/pull/33

**Comment by relaxsus** [comment]
Not fixed at the moment 😞

**Comment by 0xjmp** [comment]
Fixed in [`0.7`](https://github.com/Jakenberg/ObjectMapper-Realm/releases/tag/0.7).
