### ISSUE TITLE
Use of unresolved identifier 'ListTransform' After POD UPDATE

### ISSUE THREAD

**Issue by labrosseetdupont** [Jakenberg/ObjectMapper-Realm#37]
Hi,

I have updated ObjectMapper and now I have an error message in my realm class.
Use of unresolved identifier 'ListTransform'

When I add manualy "Struct ListTransform"  in my realm class, the error is solved.

I think the ListTransform was not imported correctly in ObjectMapper-realm...

Do you have any idea ?

Best regard's

**Comment by markus-mohemian** [comment]
@labrosseetdupont, I am experiencing the same issue. 
I am using the latest XCode 11.2 and upgraded from `0.6` => `0.9` 

The issue first appeared in version `0.7`
I suppose it was introduced by the Swift version upgrade. 

Nevertheless, I have created a PR to fix the visibility issue. 

As a workaround until the PR gets merged, you could simply pin the pod to version 0.6 by using 
`pod 'ObjectMapper+Realm', '0.6.0'`  in your Podfile.

**Comment by 0xjmp** [comment]
Fix will be out in `v1.0`. Thanks guys!

**Comment by labrosseetdupont** [comment]
Perfect !

Thank's you !!
