### ISSUE TITLE
Can't using with pod file

### ISSUE THREAD

**Issue by lexuanquynh** [Jakenberg/ObjectMapper-Realm#4]
![22](https://cloud.githubusercontent.com/assets/17588791/19110678/80ff0758-8b25-11e6-90ba-45f32e628028.png)

**Comment by 0xjmp** [comment]
What version of swift are you using? You should be using `0.1` for <=swift2.3, and `0.2` for swift 3.

**Comment by patonz** [comment]
Ive the same issue, i think with normal `pod 'ObjectMapper+Realm'` the default version is 0.1 instead of the last 0.2 
@Jakenberg  have you missed to update the pod? im trying to use
`pod 'ObjectMapper+Realm', '~> 0.2'`but the install command give me an error about wrong name or version not avaible

**Comment by 0xjmp** [comment]
Hm that is strange. I just double checked and I'm able to download `0.2` fine. Perhaps your `Podfile.lock` is configured for `0.1` already, and you just need to run `pod update ObjectMapper+Realm`?

**Comment by lexuanquynh** [comment]
thanks all. I fixed it :D 
I using pod with version 0.39.0, so I must use: pod 'ObjectMapper+Realm', '~> 0.2'
Thanks so much.
