### ISSUE TITLE
Primary key property 'id' does not exist on object

### ISSUE THREAD

**Issue by vkhadyka** [Jakenberg/ObjectMapper-Realm#44]
I try to figure out an exception:

`Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'id' does not exist on object 'Photo''`

I have the object `Photo`:

```
class Photo: Object, Mappable {
	dynamic var id: Int!
	dynamic var number: Int!
	dynamic var url: String!
	
	override class func primaryKey() -> String? {
		"id"
	}
	
	required init?(map: Map) {
	}
	
	override required init() {
		super.init()
	}
	
	func mapping(map: Map) {
		id <- map["id"]
		number <- map["num"]
		url <- map["url"]
	}
}
```

I get the exception on startup of my project. 
I use ` Realm 4.1.1`

If  I comment `primaryKey` func project starts successful.
 How can I figure out it?

**Comment by uwaisalqadri** [comment]
what's the solution?
