### ISSUE TITLE
Can't import ObjectMapper_Realm

### ISSUE THREAD

**Issue by rollr76518** [Jakenberg/ObjectMapper-Realm#8]
![2016-12-26 11 00 19](https://cloud.githubusercontent.com/assets/10362419/21474464/8e317fa8-cb5a-11e6-96bb-973e7f36f645.jpg)
Hello Sir,

I want to use ObjectMapper-Realm for my project, after I pod install it shows the error message as attachment.

My Xcode version is 8.2.1
Cocoapods version 1.1.0.rc.2
podfile is use   pod 'ObjectMapper+Realm', :git => 'https://github.com/jakenberg/ObjectMapper-Realm' and ObjectMapper+Realm version is 0.2

**Comment by NikKovIos** [comment]
Everything works correctly. I got such an error, but building project fixed it.

**Comment by 0xjmp** [comment]
@rollr76518 are you still experiencing this issue? Closing for now.

**Comment by rollr76518** [comment]
Yes, it works now, thanks!
